//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Players.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlayersCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlayersCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Players.Contracts.Resources.PlayersCodes", typeof(PlayersCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-100.
        /// </summary>
        public static string Player100TheUserAlreadyRegistred {
            get {
                return ResourceManager.GetString("Player100TheUserAlreadyRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-101.
        /// </summary>
        public static string Player101ThePlayerNotFound {
            get {
                return ResourceManager.GetString("Player101ThePlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-102.
        /// </summary>
        public static string Player102BirthDateIsInvalid {
            get {
                return ResourceManager.GetString("Player102BirthDateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-103.
        /// </summary>
        public static string Player103BirthDateIsRequired {
            get {
                return ResourceManager.GetString("Player103BirthDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-104.
        /// </summary>
        public static string Player104FirstNameIsRequired {
            get {
                return ResourceManager.GetString("Player104FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-105.
        /// </summary>
        public static string Player105FirstNameLengthIsInvalid {
            get {
                return ResourceManager.GetString("Player105FirstNameLengthIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-106.
        /// </summary>
        public static string Player106GenderIsInvalid {
            get {
                return ResourceManager.GetString("Player106GenderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-107.
        /// </summary>
        public static string Player107GenderIsRequired {
            get {
                return ResourceManager.GetString("Player107GenderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-108.
        /// </summary>
        public static string Player108LastNameIsRequired {
            get {
                return ResourceManager.GetString("Player108LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-109.
        /// </summary>
        public static string Player109LastNameLengthIsInvalid {
            get {
                return ResourceManager.GetString("Player109LastNameLengthIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestValidation-400.
        /// </summary>
        public static string RequestValidation400 {
            get {
                return ResourceManager.GetString("RequestValidation400", resourceCulture);
            }
        }
    }
}
